image: python:3.7

before_script:
  - apt-get update

test:
  script:
  - pip install .
  - python -c 'from muttlib import dbconn, utils'
  - pip install .[ipynb-utils]
  - python -c 'from muttlib import ipynb_const, ipynb_utils'
  - pip install .[forecast]
  - python -c 'from muttlib import forecast'
  - pip install .[gsheets]
  - python -c 'from muttlib import gsheetsconn'
  - pip install .[gcd]
  - python -c 'from muttlib import gcd'
  - python setup.py test

pages:
  stage: deploy
  script:
  - pip install .[dev]
  - cd docs
  - make html
  - cd ..
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master