image: python:3.7

before_script:
  - apt-get update

stages:
  - test_stage
  - deploy_stage

test:
  stage: test_stage
  script:
  - pip install .
  - python -c 'from muttlib import dbconn, utils'
  - pip install .[ipynb-utils]
  - python -c 'from muttlib import ipynb_const, ipynb_utils'
  - pip install .[forecast]
  - python -c 'from muttlib import forecast'
  - pip install .[gsheets]
  - python -c 'from muttlib import gsheetsconn'
  - pip install .[gcd]
  - python -c 'from muttlib import gcd'
  - pip install .[gdrive]
  - python -c 'from muttlib import gdrive'
  - pip install nox
  - nox --sessions tests


lint:
  stage: test_stage
  script:
    - pip install nox
    - nox --sessions cop


bandit:
  stage: test_stage
  script:
    - pip install nox
    - nox --sessions bandit


pages:
  stage: deploy_stage
  script:
  - pip install .
  - pip install .[all]
  - cd docs
  - make html -e SPHINXOPTS=-W
  - cd ..
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master


# Deploy from master to package registry
# If PYPI_USERNAME/PYPI_PASSWORD are not set, defaults to gitlab
# package registry, thus using the required variables to do so
# The package will be uploaded to PYPI_URL, which can be overrided
# not to upload to gitlab's PYPI
deploy:
  stage: deploy_stage
  only:
    refs:
      - master
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - export TWINE_USERNAME=${PYPI_USERNAME:=gitlab-ci-token}
    - export TWINE_PASSWORD=${PYPI_PASSWORD:=$CI_JOB_TOKEN}
    - export PYPI_REPO=${PYPI_URL:=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi}
    - python -m twine upload --verbose --repository-url ${PYPI_REPO} dist/*

