name: publish
on: push

jobs:
    pypi-publish:
        if: startsWith(github.ref, 'refs/tags/')
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
          name: pypi
          url: https://pypi.org/p/muttlib
        permissions:
          id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
        # retrieve your distributions here
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1

    publish-to-testpypi:
        name: Publish Python 🐍 distribution 📦 to TestPyPI
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/muttlib
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
        - name: Publish distribution 📦 to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/