# TODO: remove; just a sample workflow, nothing to see here
name: test

on:
  push:

jobs:
  bandit:
    name: Bandit
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install nox
        run: pip install -U nox
      - name: Run bandit
        run: nox --sessions bandit
