name: validate

on: [pull_request]

env:
  POETRY_VERSION: 1.6.1

jobs:
  check_version:
    if: github.base_ref == 'master'
    runs-on: [self-hosted]
    container:
      image: python:3.10
    steps:
      - name: Update base image
        run: |
          apt update
          apt install -y libkrb5-dev libsasl2-dev
          pip install poetry==$POETRY_VERSION
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install packaging
      - name: Fetch source ref
        run: git fetch origin $GITHUB_HEAD_REF
      - name: Fetch target ref
        run: git fetch origin $GITHUB_BASE_REF
      - name: Check version
        run: |
          lib_ver=$(git diff origin/$GITHUB_HEAD_REF origin/$GITHUB_BASE_REF -- .bumpversion.cfg | grep "current_version" | cut -d = -f 2 | xargs)
          ver_new=$(echo $lib_ver | cut -f1 -d' ')
          ver_old=$(echo $lib_ver | cut -f2 -d' ')
          echo "new version: $ver_new (vs) old version: $ver_old"
          python -c "import sys; from packaging import version; exit(not version.parse(sys.argv[1]) > version.parse(sys.argv[2]))" $ver_new $ver_old
          exit_status=$?
          if [ $exit_status -eq 1 ]; then echo "Error comparing versions"; fi;
          exit $exit_status

  check_changelog:
    if: github.base_ref == 'master'
    runs-on: [self-hosted]
    container:
      image: python:3.10
    steps:
      - name: Update base image
        run: |
          apt update
          apt install -y libkrb5-dev libsasl2-dev
          pip install poetry==$POETRY_VERSION
      - uses: actions/checkout@v4
      - name: Fetch source ref
        run: git fetch origin $GITHUB_HEAD_REF
      - name: Fetch target ref
        run: git fetch origin $GITHUB_BASE_REF
      - name: Check changed lines
        run: |
          added_lines=$(git diff --numstat origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF -- CHANGELOG.md | awk '{print $1}')
          if [ -z $added_lines ] || [ $added_lines -eq 0 ]; then echo "Changelog has NOT been modified" && exit 1; else echo "Changelog has been modified" && exit 0; fi;
