name: linters
on: [pull_request, push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
      - name: Update base image
        run: |
          apt update
          apt install -y libkrb5-dev libsasl2-dev
          pip install poetry
      - uses: actions/checkout@v2
      - name: Set tag output
        run: echo "::set-output name=tag_name::v$(grep current_version .bumpversion.cfg | cut -d= -f2 | xargs)"
      - name: Create Tag
        uses: actions/github-script@v3
        env:
           TAG: ${{ steps.set-tag.outputs.tag_name }}
        with:
           github-token: ${{ github.token }}
           script: |
             github.git.createRef({
               owner: context.repo.owner,
               repo: context.repo.repo,
              ref: "refs/tags/${{ steps.set-tag.outputs.tag_name }}",
               sha: context.sha
             })
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
           tag: ${{ steps.set-tag.outputs.tag_name }}
           bodyFile: './CHANGELOG.md'
           token: ${{ secrets.GITHUB_TOKEN }}
