name: version

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches: [master]
  push:
    branches:
      - master

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: [self-hosted]
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v4

      - name: Get muttlib version
        id: version
        run: |
          grep current_version .bumpversion.cfg | cut -d= -f2 | xargs >>$GITHUB_OUTPUT

      - name: Extract release notes from changelog
        id: release_notes
        run: |
          version=${{ steps.version.outputs.version }}
          release_notes=$(sed -n "/^## \[$version\]/,/^## /p" ./CHANGELOG.md | sed '1d;$d')
          echo "$release_notes" >>$GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body: |
            ${{ steps.release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
