name: version
on:
  pull_request:
    types:
      - closed
    branches: [master]

jobs:
  create_github_release:
    name: Create GitHub Release
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: [self-hosted]
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v4

      - name: Get muttlib version
        id: version
        run: |
          echo "::set-output name=version::$(grep current_version .bumpversion.cfg | cut -d= -f2 | xargs)"

      - name: Extract release notes
        id: release_notes
        run: |
          version=${{ steps.version.outputs.version }}
          release_notes=$(sed -n "/^## \[$version\]/,/^## /p" ./CHANGELOG.md | sed '1d;$d')
          echo "::set-output name=release_notes::$release_notes"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body: ${{ steps.release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
